l10n:
  arb_dir: lib/l10n
  template_arb_file: app_en.arb
  output_localization_file: app_localizations.dart
  output_class: AppLocalizations
  sync_files: true
  untranslatable_strings:
    - "app_name"
