/drop
/add       l10n.yaml
/add       lib/l10n/app_en.arb
/add       lib/main_screen.dart
/add       lib/settings_screen.dart
/add       lib/simple_location_service.dart
/add       lib/status_screen.dart
