name: traccar_client
description: "Traccar Client"
publish_to: 'none'
version: 9.5.2+106

environment:
  sdk: ^3.5.0

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl: any
  geolocator: ^13.0.1
  shared_preferences: ^2.5.3
  quick_actions: ^1.1.0
  rate_my_app: ^2.3.2
  shared_preferences_android: ^2.4.7
  mobile_scanner: ^6.0.0
  flutter_secure_storage: ^9.2.4
  http: ^1.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  generate: true
