name: traccar_client
description: "Traccar Client"
publish_to: 'none'
version: 9.5.5+113

environment:
  sdk: ">=3.2.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl: any
  geolocator: ^10.0.1
  shared_preferences: ^2.2.2
  quick_actions: ^1.1.0
  rate_my_app: ^2.2.0
  shared_preferences_android: ^2.2.1
  mobile_scanner: ^3.5.5
  flutter_secure_storage: ^8.0.0
  http: ^1.1.0
  battery_plus: ^4.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  generate: true
