name: Build APK

on:
  push:
    branches: [ main ]
    tags: [ 'v*' ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.19.3'
          channel: 'stable'
          cache: true
          
      - name: Set Flutter SDK version
        run: |
          echo "Setting Flutter SDK version to match pubspec.yaml"
          sed -i 's/^  sdk: \^3.2.0/  sdk: ">=3.2.0 <4.0.0"/' pubspec.yaml

      - name: Get dependencies
        run: flutter pub get

      - name: Fix Flutter embedding
        run: |
          # Create a temporary Flutter project to get the correct embedding files
          mkdir -p temp_project
          cd temp_project
          flutter create --platforms=android temp_app
          cd ..
          
          # Copy the io.flutter.* packages from the temp project
          mkdir -p android/app/src/main/java/io/flutter/embedding/
          mkdir -p android/app/src/main/java/io/flutter/plugins/
          mkdir -p android/app/src/main/java/io/flutter/view/
          
          # Copy the GeneratedPluginRegistrant.java file
          cp -r temp_project/temp_app/android/app/src/main/java/io/flutter/plugins/GeneratedPluginRegistrant.java android/app/src/main/java/io/flutter/plugins/ || true
          
          # Clean up
          rm -rf temp_project
          
      - name: Build APK
        run: flutter build apk --release

      - name: Get version from pubspec
        id: version
        run: |
          VERSION=$(grep '^version:' pubspec.yaml | cut -d ' ' -f 2 | cut -d '+' -f 1)
          echo "version=$VERSION" >> $GITHUB_OUTPUT

      - name: Rename APK
        run: |
          mv build/app/outputs/flutter-apk/app-release.apk \
             build/app/outputs/flutter-apk/traccar-client-degoogled-v${{ steps.version.outputs.version }}-simple.apk

      - name: Upload APK artifact
        uses: actions/upload-artifact@v4
        with:
          name: traccar-client-degoogled-v${{ steps.version.outputs.version }}-simple
          path: build/app/outputs/flutter-apk/traccar-client-degoogled-v${{ steps.version.outputs.version }}-simple.apk

      - name: Upload to Release (if tag)
        if: startsWith(github.ref, 'refs/tags/')
        uses: softprops/action-gh-release@v1
        with:
          files: build/app/outputs/flutter-apk/traccar-client-degoogled-v${{ steps.version.outputs.version }}-simple.apk
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}